version: "3"
services:
  app:
    container_name: docker-live
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229/tcp
    expose:
      - 9229
    command: npm run dev

# docker-compose up --detach
# docker-compose up --force-recreate --detach
# docker-compose run --rm --detach --service-ports node bash

# docker start docker-live
# docker stop docker-live

# docker container rm --force docker-live
